spring:
  application:
    name: notes-service # name of service
  cloud:
    config:
      uri: http://localhost:8888/ # url of config-service
      fail-fast: true # fails if cannot connect to config-service
      name: service-registry-client, jwt-security # what properties files to load
  profiles:
    active: eureka # active profiles
  h2:
    console:
      enabled: true